name: 'Update by stargazed'
# This workflow runs at 00:30 everyday
on:
  workflow_dispatch:
  schedule:
    -
      cron: '30 0 * * *'
jobs:
  build:
    name: 'stargazed update'
    runs-on: ubuntu-latest
    steps:
      -
        name: 'Use GitHub Actions'
        uses: actions/checkout@v3.2.0
      
      - 
        name: 'Setup Node.js environment'
        uses: actions/setup-node@v2.5.2

      -
        name: 'Install Package'
        run: 'npm install --global stargazed'
      -
        name: 'Update Repo'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: 'stargazed --username  "hiyorijl" --token ${GITHUB_TOKEN} --repo "all-my-repo-stars" --message "stargazed update by update-stargazed.yml" --sort'

